In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import cv2
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from sklearn.preprocessing import OneHotEncoder


In [2]:
(train_X, train_Y), (test_X, test_Y) = mnist.load_data()

for i in range(20):
  plt.figure(i)
  image = np.array(train_X[i])
  # plt.imshow(train_X[i], cmap='gray')

print(train_Y)

dataset_train_y = pd.DataFrame(train_Y)
dataset_train_y.head()

dataset_test_y = pd.DataFrame(train_Y)
dataset_test_y.head()

onehotencoder = OneHotEncoder()
train_Y = onehotencoder.fit_transform(dataset_train_y).toarray()
print(train_Y)

print(' ')

test_Y = onehotencoder.fit_transform(dataset_test_y).toarray()
print(test_Y)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, kernel_size=3, activation='relu', input_shape=(28, 28, 1)))
model.add(tf.keras.layers.Conv2D(64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.save('digitrecog1')

print(train_X.shape)
print(train_Y.shape)

# model.fit(train_X, train_Y, epochs=10, steps_per_epoch=10)
model.fit(train_X, train_Y, epochs=10)


11501568/11490434 [==============================] - 0s 0us/step
[5 0 4 ... 5 6 8]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
 
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
INFO:tensorflow:Assets written to: digitrecog1/assets
(60000, 28, 28)
(60000, 10)
Epoch 1/10
1875/1875 [==============================] - 154s 81ms/step - loss: 0.3949 - accuracy: 0.9510
Epoch 2/10
1875/1875 [==============================] - 149s 80ms/step - loss: 0.0713 - accuracy: 0.9778
Epoch 3/10
1875/1875 [==============================] - 148s 79ms/step - loss: 0.0467 - accuracy: 0.9859
Epoch 4/10
1875/1875 [==============================] - 154s 82ms/step - loss: 0.0347 - accuracy: 0.9891
Epoch 5/10
1875/1875 [==============================] - 155s 83ms/step - loss: 0.0293 - accuracy: 0.9

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

In [4]:
print(len(train_X))
print(len(train_Y))


print(train_X.shape)
print(train_Y.shape)

print(test_X.shape)
print(test_Y.shape)

prediction_y = model.predict(test_X)
accuracy = model.evaluate(prediction_y, test_Y)

60000
60000
(60000, 28, 28)
(60000, 10)
(10000, 28, 28)
(60000, 10)


ValueError: ignored