In [12]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf

In [15]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [18]:
greeting = tf.Variable("yo", tf.string)

In [19]:
tf.rank(greeting)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [44]:
moreGreetings = tf.Variable([[[["3.987", "9.812"], ["4.4912931", "9.716"], ["6.5094", "9.1922"]]]], tf.float64)

In [45]:
tf.rank(moreGreetings)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [46]:
moreGreetings.shape

TensorShape([1, 1, 3, 2])

In [12]:
array = tf.ones([1,2,3])

In [8]:
print(array)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [16]:
array2 = tf.reshape(array, [3, 2, 1])

In [17]:
print(array2)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


In [1]:
import matplotlib.pyplot as plt
